array_width = 60
attr_fn_like_width = 70
chain_width = 60
edition = "2018"
fn_args_layout = "Tall"
fn_call_width = 60
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
max_width = 100
merge_derives = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 50
struct_lit_width = 18
struct_variant_width = 35
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = false
